name: scahpy_env
channels:
  - conda-forge
dependencies:
  - python==3.11
  - xarray
  - dask
  - netCDF4
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - cmocean
  - cmcrameri
  - pyshp
  - pip
  - pip:
     - scahpy
     
