lang: en-US
metadata-files: ["_language-en.yml"]

project:
  output-dir: _site/en
  render:
    - 01_install_en.qmd
    - 02_use_en.qmd
    - 03_tutorial_01_en.qmd
    - 03_tutorial_02_en.qmd
    - 03_tutorial_03_en.qmd
    - 04_API_en.qmd
    - 05_contrib_en.qmd
    - 06_references_en.qmd
    - index_en.qmd
    - api_en/*.qmd

website:
  sidebar:
    style: "docked"
    title: "DOCUMENTATION"
    logo: assets/cover.png
    search: true
    collapse-level: 1
    contents:
      - text: "Introduction"
        href: index_en.qmd

      - text: "Installation"
        href: 01_install_en.qmd

      - text: "Usage"
        href: 02_use_en.qmd

      - section: "Tutorials"
        contents:
          - text: "Tutorial 1: Reading WRF"
            href: 03_tutorial_01_en.qmd
          - text: "Tutorial 2: Reading CROCO"
            href: 03_tutorial_02_en.qmd
          - text: "Tutorial 3: Basic Plots"
            href: 03_tutorial_03_en.qmd

      - section: "Help & References"
        contents:
          - text: "API Reference"
            href: 04_API_en.qmd
          - text: "Contributing"
            href: 05_contrib_en.qmd
          - text: "References"
            href: 06_references_en.qmd

format:
  html:
    toc: true
    include-after-body: _includes/lang-switch.html
