lang: es-PE
metadata-files: ["_language-es.yml"]

project:
  render:
    - es/index.qmd
    - es/01_install.qmd
    - es/02_use.qmd
    - es/03_tutorial_01.qmd
    - es/03_tutorial_02.qmd
    - es/03_tutorial_03.qmd
    - es/04_API.qmd
    - es/05_contrib.qmd
    - es/06_references.qmd


website: 
  sidebar:
    style: "docked"
    title: "DOCUMENTACIÓN"
    logo: assets/cover.png
    search: true
    collapse-level: 1
    contents:
      - text: "Introducción"
        href: es/index.qmd

      - text: "Instalación"
        href: es/01_install.qmd

      - text: "Uso"
        href: es/02_use.qmd

      - section: "Tutoriales"
        contents:
          - text: "Tutorial 1: Lectura de WRF"
            href: es/03_tutorial_01.qmd
          - text: "Tutorial 2: Lectura de CROCO"
            href: es/03_tutorial_02.qmd
          - text: "Tutorial 3: Gráficos básicos"
            href: es/03_tutorial_03.qmd

      - section: "Ayuda y referencias"
        contents:
          - text: "Referencia de la API"
            href: es/04_API.qmd
          - text: "Contribuir"
            href: es/05_contrib.qmd
          - text: "Referencias"
            href: es/06_references.qmd

format:
  html:
    toc: true
    include-after-body: _includes/lang-switch.html
