project:
  output-dir: _site/en

lang: en-US
language: _language-en.yml 

website:
  navbar:
    left:
      - text: "Home"
        href: en/index.qmd
      - text: "Install"
        href: en/01_install.qmd
      - text: "Usage"
        href: en/02_use.qmd
      - text: "Tutorials"
        menu:
          - en/03_tutorial_01.qmd
          - en/03_tutorial_02.qmd
          - en/03_tutorial_03.qmd
      - text: "API"
        href: en/04_API.qmd

      - text: "References"
        href: en/references.qmd

    right:
      - text: ES
        href: ../es/

  sidebar:
    style: floating
    search: true
    contents:
      - section: "Guide"
        contents:
          - en/index.qmd
          - en/01_install.qmd
          - en/02_use.qmd
      - section: "Tutorials"
        contents:
          - en/03_tutorial_01.qmd
          - en/03_tutorial_02.qmd
          - en/03_tutorial_03.qmd
      - section: "Reference"
        contents:
          - en/04_API.qmd
          - en/05_contrib.qmd
          - en/references.qmd


