project:
  output-dir: _site/en

lang: en
language: _language-en.yml   # opcional

website:
  navbar:
    left:
      - text: "Home"
        href: en/index.qmd
      - text: "Install"
        href: en/01_install.qmd
      - text: "Usage"
        href: en/02_use.qmd
      - text: "Tutorials"
        menu:
          - en/03_tutorial_01.qmd
          - en/03_tutorial_02.qmd
          - en/03_tutorial_03.qmd
      - text: "Gallery"
        href: en/gallery.qmd
      - text: "API"
        href: en/04_API.qmd
      - text: "Benchmarks"
        href: en/benchmarks.qmd
      - text: "FAQ"
        href: en/faq.qmd
    right:
      - text: ES
        href: /SCAHpy/es/

bibliography: en/references.bib


