project:
  type: website

profiles: [es, en]

website:
  title: "SCAHpy"
  site-url: https://fiorelacl.github.io/SCAHpy
  repo-url: https://github.com/fiorelacl/SCAHpy
  repo-actions: [issue, source]
  favicon: assets/cover.png
  sidebar:
    style: floating
    search: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    number-sections: true
    df-print: paged
execute:
  freeze: auto
  echo: true
  warning: false
  message: false