project:
  output-dir: _site/es

lang: es
language: _language-es.yml

website:
  navbar:
    left:
      - text: "Inicio"
        href: es/index.qmd
      - text: "Instalación"
        href: es/01_install.qmd
      - text: "Uso"
        href: es/02_use.qmd
      - text: "Tutoriales"
        menu:
          - es/03_tutorial_01.qmd
          - es/03_tutorial_02.qmd
          - es/03_tutorial_03.qmd
      - text: "API"
        href: es/04_API.qmd
      - text: "Referencias"
        href: es/references.qmd
    right:
      - text: EN
        href: ../en/

  sidebar:
    style: floating
    search: true
    contents:
      - section: "Guía"
        contents:
          - es/index.qmd
          - es/01_install.qmd
          - es/02_use.qmd
      - section: "Tutoriales"
        contents:
          - es/03_tutorial_01.qmd
          - es/03_tutorial_02.qmd
          - es/03_tutorial_03.qmd
      - section: "Referencia"
        contents:
          - es/04_API.qmd
          - es/05_contrib.qmd
          - es/references.qmd




