project:
  type: website

profile:  
  default: english
  group: [english, spanish]

website:
  title: 'SCAHpy'
  favicon: assets/logo.png
  page-footer: "Copyright 2025, Fiorela Castill√≥n"
  bread-crumbs: false
  sidebar:
    tools:
      - icon: filetype-py
        href: https://pypi.org/project/scahpy/
      - icon: github
        href: https://github.com/fiorelacl/SCAHpy/

format:
  html:
    theme:
      light:
        - brite
        - scahpy.scss
    include-before-body: _includes/announcement.html
    max-width: 100%     # o incluso 100% si quieres
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: scroll
    code-block-bg: "#f3f9ee"
    code-block-border-left: "#0c447d"
    number-sections: false
    df-print: paged

execute:
  enabled: false
  echo: true
  warning: false
  message: false
