project:
  type: website

group:
  - [spanish, english] 

quartodoc:
  style: pkgdown
  dir: api
  package: scahpy
  sections:
    - title: "IO Atmosférico (WRF)"
      desc: "Funciones para lectura, manejo de coordenadas y diagnósticos atmosféricos WRF."
      contents:
        - components.atmos

    - title: "IO Oceánico (CROCO)"
      desc: "Funciones para lectura, coordenadas y diagnósticos del modelo oceánico CROCO."
      contents:
        - components.ocean

    - title: "Core (Operaciones esenciales)"
      desc: "Operaciones comunes de coordenadas, tiempo, vertical y utilidades."
      contents:
        - core

    - title: "Plotting"
      desc: "Funciones de visualización para mapas, secciones y series de tiempo."
      contents:
        - plots

website:
  title: 'SCAHpy'
  favicon: assets/logo.png
  page-footer: "Copyright 2025, Fiorela Castillón"
  bread-crumbs: false
  sidebar:
    tools:
      - icon: filetype-py
        href: https://pypi.org/project/scahpy/
      - icon: github
        href: https://github.com/fiorelacl/SCAHpy/

format:
  html:
    theme:
      light:
        - brite
        - scahpy.scss
    include-before-body: _includes/announcement.html
    max-width: 100%     # o incluso 100% si quieres
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: scroll
    code-block-bg: "#f3f9ee"
    code-block-border-left: "#0c447d"
    number-sections: false
    df-print: paged

execute:
  enabled: false
  echo: true
  warning: false
  message: false
